{
  if (Sys.info()[1]=="Linux") {
    source("~/R/functions/ss.png.r")
    source("~/R/functions/ss.html.r")
    source("~/R/functions/contents.r")
    source("~/R/functions/phest.r")
    source("~/R/functions/phest.plot.r")
    source("~/R/functions/Legend.r")
    source("~/R/functions/footnote.r")
    source("~/R/functions/sspeelit1.r")
    source("~/R/functions/theil.r")
    source("~/R/functions/tit.r")
    source("~/R/functions/ordplt.r")
    source("~/R/functions/ss.desc.r")
    source("~/R/functions/CrossTable.r")
    source("~/R/functions/myboxp.r")
  }
  else if (Sys.info()[1]=="Windows") {
    source("z:/R/functions/ss.png.r")
    source("z:/R/functions/ss.html.r")
    source("z:/R/functions/contents.r")
    source("z:/R/functions/phest.r")
    source("z:/R/functions/phest.plot.r")
    source("z:/R/functions/Legend.r")
    source("z:/R/functions/footnote.r")
    source("z:/R/functions/sspeelit1.r")
    source("z:/R/functions/theil.r")
    source("z:/R/functions/tit.r")
    source("z:/R/functions/ordplt.r")
    source("z:/R/functions/ss.desc.r")
    source("z:/R/functions/CrossTable.r")
    source("z:/R/functions/myboxp.r")
  }
}
